name: Azure Deploy Dating Agent

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js (for azd)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Azure Developer CLI
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          azd version

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up azd environment
        run: |
          azd env set AGENT_LOG_FILE /tmp/agent.log
          azd env set PORT 8000
          # Set your API keys and REDIS_URL here or in Azure portal

      - name: Provision Azure infra (if needed)
        run: azd provision

      - name: Deploy backend (agent) service
        run: azd deploy --service backend

      - name: Show outputs
        run: azd env get-values 